name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:    # Manual trigger uchun

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Wasm
        run: |
          chmod +x ./gradlew
          ./gradlew wasmJsBrowserDistribution

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GIT }}
          publish_dir: ./build/dist/wasmJs/productionExecutable
          cname: wincoapp.com